services:
  postgres:
    image: postgres:16
    container_name: internal-transfers-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: internal_transfers
      POSTGRES_USER: internal_transfers
      POSTGRES_PASSWORD: internal_transfers
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: